---
title: "Survival Model Testing"
author: "Becky Scurlock"
date: '2022-06-10'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
# Load libraries
library("tidyverse")
library("survival")
library("survminer")
library("ggplot2")
library("ggfortify")
library("flexsurv")
library("lubridate")

# Load data
df_all = read.csv("../data/individual_data.csv")
df_all = df_all %>% 
  mutate(
    treatment_time = ymd(treatment_time),
    cens_event_time_lb = ifelse(death == 0, follow_up_time, event_time_lb), 
    cens_event_time_ub = ifelse(death == 0, follow_up_time, event_time_ub),
    left_interval = interval(treatment_time, cens_event_time_lb) %/% days(1), 
    right_interval = interval(treatment_time, cens_event_time_ub) %/% days(1),
    censoring = ifelse(death == 0, 0, ifelse(left_interval == right_interval, 1, 3)),
    right_interval = right_interval + ifelse(left_interval == 0, 1, 0),
    left_interval = left_interval + ifelse(left_interval == 0, 1, 0)
  )
```

```{r}
head(df_all)
```

```{r}
df_all %>% 
  group_by(study) %>% 
  filter(death == 1) %>% 
  summarise(round(mean(right_interval - left_interval)))
```

# Kaplan-Meier Curves
```{r}
# Plot K-M curves for each study
studies <- unique(df_all$study)
studies <- studies[2:10]  #Q: Why don't Chiller or Luby work?
i = 1
for (study in studies) {
  # Compute Kaplan-Meier estimates of survival probability over time
  df_study = df_all[which(df_all$study == study),]
  km_fit <- survfit(Surv(left_interval, right_interval, death, type = "interval") ~
    as.factor(wtreatment), data = df_study, type = "kaplan-meier")
  
  # Plot Kaplan-Meier curves
  print(autoplot(km_fit) + xlab("Time After Treatment (Days)") + 
    ylab("Survival Probability") + ggtitle(paste("K-M:", study)) + theme_bw())
  i = i + 1
}
```

```{r}
# Plot K-M curves for each study
studies <- unique(df_all$study)
i = 1
for (study in studies) {
  # Compute Kaplan-Meier estimates of survival probability over time
  # (include only children alive at time of treatment)
  df_study = df_all[which(df_all$study == study & df_all$age_month >= 0),]
  km_fit <- survfit(Surv(age_month, death, type = "right") ~
    as.factor(wtreatment), data = df_study, type = "kaplan-meier")
  
  # Plot Kaplan-Meier curves
  print(autoplot(km_fit) + xlab("Age at Baseline(Months)") + 
    ylab("Survival Probability") + ggtitle(paste("K-M:", study)) + theme_bw())
  i = i + 1
}
```

# Summaries of Deaths over Time
```{r}
# Function to compute counts in each bin 
var_count <- function(var) {
  return(c(sum(var < 7, na.rm = T), sum(var < 30, na.rm = T), 
    sum(var < 60, na.rm = T), sum(var < 90, na.rm = T)))
}

event_counts <- function(df) {
  return(c(var_count(df$right_interval), var_count(df$left_interval)))
}

# Split by groups
df_list = df_all %>%
  filter(death == 1) %>% 
  select(study, left_interval, right_interval, death) %>%
  group_by(study) %>%
  group_split()

counts = matrix(NA, length(df_list), 8)
colnames(counts) = c("First Week (LB)", "First Month (LB)", "First 2 Months (LB)", 
  "First 3 Months (LB)", "First Week (UB)", "First Month (UB)", 
  "First 2 Months (UB)", "First 3 Months (UB)")
rownames(counts) = df_list %>% lapply(function(df) unique(df$study))
  
for (i in 1:length(df_list)) {
  counts[i,] = event_counts(df_list[[i]])
}

print(counts)
```
