---
title: "TakeUp Distance Assignment"
format: html
editor: source 
---

```{r}
#| label: setup

library(magrittr)
library(tidyverse)
library(sf)
library(here)


source(here("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
source(here("analysis_util.R"))
source(here("dist_structural_util.R"))

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
#| label: load-geo-data

wgs.84 <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
kenya.proj4 <- "+proj=utm +zone=36 +south +ellps=clrk80 +units=m +no_defs"

rct.schools.data <- read_rds(here("data", "takeup_rct_schools.rds"))
load(here("data", "takeup_village_pot_dist.RData"))
load(here("data", "analysis.RData"))

schools <- st_as_sf(rct.schools.data, crs = wgs.84)
villages <- village.centers %>% 
  st_as_sf(coords = c("lon", "lat"), crs = wgs.84)
```

```{r}
#| fig-width: 8

ggplot(schools) +
  geom_sf(aes(color = "Schools"), size = 0.5) +
  geom_sf(aes(color = "Villages"), data = villages) +
  scale_color_manual("", values = c("Schools" = "black", "Villages" = "red"))
```

```{r}
villages %<>% 
  mutate(
    dist_to_closest_school = st_transform(., kenya.proj4) %>% 
      st_distance(st_transform(schools, kenya.proj4)) %>%
      plyr::alply(1, min) %>% 
      unlist()
  )
```

```{r}
villages %>% 
  ggplot(aes(dist_to_closest_school)) +
  geom_histogram(aes(y = stat(density)), binwidth = 100, alpha = 0.5) +
  labs(x = "Distance to Closest School", y = "Density")

villages %>% 
  ggplot(aes(dist_to_closest_school)) +
  geom_histogram(aes(y = stat(density), fill = dist.pot.group), position = "identity", binwidth = 100, alpha = 0.5) +
  scale_fill_discrete("Distance Assignment", labels = str_to_title) +
  labs(x = "Distance to Closest School", y = "Density")
```



```{r}


villages %>% 
  select(dist.to.pot, dist_to_closest_school) %>%
  filter(dist.to.pot == dist_to_closest_school)

villages %>%
  summarise(n_vills = n_distinct(cluster.id))

all_vill_school_pairs = villages %>% 
  st_join(
    x = .,
    y = st_transform(schools, kenya.proj4),
    join = st_is_within_distance, 
    dist = 1500,
    left = TRUE
  ) 

all_vill_school_distances = st_distance(
  villages, 
  schools
)

expected_distance = apply(all_vill_school_distances, FUN = function(x){mean(x[x < 1500])}, MARGIN = 1)

villages$expected_distance = expected_distance



villages %>%
  lm()
all_vill_school_pairs %>%
  colnames()
all_vill_school_pairs %>%
  select(cluster.id.x, cluster.id.y)
all_vill_school_pairs %>%
  filter(dist.to)


all_vill_school_pairs %>%
  mutate(
    dist_to_closest_school = st_transform(., kenya.proj4) %>% 
      st_distance(st_transform(schools[schools$cluster.id == .$cluster.id.y], kenya.proj4)) %>%
      plyr::alply(1, unique) %>% 
      unlist()
  )

all_vill_school_pairs %>%
  select(dist_to_school)
```

